# Override properties in environment variables using screaming snake case
# e.g. GURU_USERNAME overrides guru.username.
# Override properties in command line using --property.name
# e.g. --guru.username overrides guru.username.

spring:
  profiles:
    active:
      - dog
      - EN
      - dev
guru:
  username: YmlUserName
  password: YmlPassword
  jdbcUrl: YmlUrl
  
---
spring:
  profiles: prod
guru:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcUrl: YmlProdUrl